trigger:
  branches:
    include:
      - main
  paths:
    include:
      - backend/**

pool:
  vmImage: ubuntu-latest

variables:
  imageTag: '$(Build.BuildId)'

steps:

# ==========================================
# BUILD AND PUSH BACKEND IMAGE TO ACR
# ==========================================

- checkout: self

- task: Docker@2
  displayName: Build and Push Backend
  inputs:
    containerRegistry: 'ACR-Service-Connection'
    repository: 'backend'
    command: 'buildAndPush'
    Dockerfile: 'backend/Dockerfile'
    buildContext: 'backend'
    tags: |
      $(imageTag)
      latest


# ==========================================
# DEPLOY BACKEND TO PRIVATE VM
# ==========================================

- task: AzureCLI@2
  displayName: Deploy Backend to Private VM
  inputs:
    azureSubscription: 'Azure-Service-Connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |

      az vm run-command invoke \
        --resource-group devops-resrce \
        --name backend-vm \
        --command-id RunShellScript \
        --scripts "

          set -e

          echo 'Logging into Azure using VM managed identity...'

          az login --identity

          echo 'Logging into Azure Container Registry...'

          az acr login --name acrcontainerproject123

          echo 'Pulling new backend image...'

          docker pull acrcontainerproject123.azurecr.io/backend:$(Build.BuildId)

          echo 'Stopping old backend container...'

          docker stop backend || true

          echo 'Removing old backend container...'

          docker rm backend || true

          echo 'Starting new backend container...'

          docker run -d \
            --name backend \
            --network app-net \
            --restart unless-stopped \
            -e DB_HOST=postgres \
            -e DB_NAME=DB-VAR \
            -e DB_USER=postgres \
            -e DB_PASSWORD='DB-PASS' \
            -e REDIS_URL=redis://redis:6379 \
            -p 5000:5000 \
            acrcontainerproject123.azurecr.io/backend:$(Build.BuildId)

          echo 'Waiting for backend...'

          sleep 10

          echo 'Running containers:'

          docker ps

          echo 'Backend health check:'

          curl http://localhost:5000/health

          echo ''
          echo 'Backend deployment completed successfully.'

        "
